### ISSUE TITLE
format.js RangeError: Invalid string length

### ISSUE THREAD

**Issue by Yaodeowo** [PrismarineJS/prismarine-chat#108]
return string.replace(/%(?:(\d+)\$)?(s|%)/g, (g0, g1) => {
                ^

RangeError: Invalid string length

Node.js v18.17.1

my fix code:
module.exports = format

function format (string, _with = []) {
  let i = 0

  return string.replace(/%(?:(\d+)\$)?(s|%)/g, (g0, g1) => {
    if (g0 === '%%') {
      return '%'
      const idx = g1 ? parseInt(g1) - 1 : i++
      if (_with[idx] !== undefined && _with[idx].length !== undefined) {
		if (_with[idx].length > 5000) return "";
      };
      if (_with[idx] !== undefined) {
        return _with[idx]
      } else {
        return ''
      }
    }
  })
}

// i hope can add the limit

**Comment by extremeheat** [comment]
Dupe #106

**Comment by Yaodeowo** [comment]
> Dupe #106

NAH
