### ISSUE TITLE
Add 1.16 hex color support

### ISSUE THREAD

**Issue by wvffle** [PrismarineJS/prismarine-chat#6]
1.16 provides full rgb support with hex values.

An example chat component: `{ text: 'hello', color: '#00AAFF' }` which should render text as blue

![IMG_20200804_183937.jpg](https://user-images.githubusercontent.com/13330620/89321442-3ff06380-d683-11ea-8c73-91cba5142a99.jpg)

**Comment by Nurutomo** [comment]
```js
If (majorVersion == '1.16' && color[0] == '#') {
  // TODO: Hex Coloring
}```

**Comment by Kashalls** [comment]
Any updates on this? Currently experiencing this spammy message as well. (This is occurring because of scoreboard updates.)
https://uwu.whats-th.is/4j2GsrB.png

**Comment by rom1504** [comment]
warning are now not displayed by default (https://github.com/PrismarineJS/prismarine-chat/commit/72d608cac21c65b3249a327e2e34db0d171e27af)
However people should really learn to hide output from commands

**Comment by Kashalls** [comment]
This error was not able to be hidden if you used the message event and tried using the method "toAnsi()". It would throw this error to console.log and there was nothing you could do about it until the temp fix.
