### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by phorcys420** [PrismarineJS/prismarine-chat#60]
I [PR](https://github.com/PrismarineJS/prismarine-chat/pull/59)'d a fix to the typedefs ~a month ago, but I realised that it still errors on any new install due to the fact that the version stayed the same.

The real issue lies in [prismarine-entity](https://github.com/PrismarineJS/prismarine-entity) though, due to the fact that it requires an "outdated" (non-fixed) version it also breaks typedefs under there.

So the thing to do would be

1. Set version >1.5.0
2. Update it in prismarine-entity

**Comment by rom1504** [comment]
No versions don't work like this with npm and semver
The only thing to do is make a release PR in prismarine-chat
You can do that by doing the same as the many previous release PR (search in GitHub)
