### ISSUE TITLE
%

### ISSUE THREAD

**Issue by CNWMakesCode** [PrismarineJS/prismarine-chat#71]
/tellraw bot_username "%" crashes the bot.

**Comment by business-fox** [comment]
making a try-catch for the chat will fix this. however #83 should also fix this issue.

**Comment by lginlangl** [comment]
This is now fixed as of commit [3e2eb58](https://github.com/PrismarineJS/prismarine-chat/commit/3e2eb58fb6fc1a5df11e6d4e1e2cb511a46f0bf5)

**Comment by extremeheat** [comment]
Make a release PR to fix
