### ISSUE TITLE
Broken type definition

### ISSUE THREAD

**Issue by IceTank** [PrismarineJS/prismarine-chat#80]
Commit https://github.com/PrismarineJS/prismarine-chat/commit/feb7d1f668f04690385ff56ea32cf81fa8f27dfd broke type definitions for prismarine chat. 
All typescript projects using `ChatMessage` are failing to compile on prismarine-chat version 1.7.x. 1.6.x works fine.

**Comment by extremeheat** [comment]
Old, should be fixed
