### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'formatString')

### ISSUE THREAD

**Issue by anch0vie** [PrismarineJS/prismarine-chat#92]
**Describe the bug**
Every time the bot receives chat, whether from the chat automation of the bot itself or other players, the bot crashes.

**To Reproduce**
1. Create an offline mode server with Purpur server software.
2. Launch the server.
3. Activate [the AFK bot](https://github.com/urFate/Afk-Bot) made by urFate.
4. Wait for the bot receives chat.
5. Crash.

**Crash log**
https://pastebin.com/hB7iZu0z

**Expected behavior**
The bot should run with no crashes.

**Bot config*
https://pastebin.com/cDzraSZH

**Additional information**
This issue was already submitted to AFK bot's github page but the developer made me submit it here since he said the problem comes from here.

**Comment by frej4189** [comment]
Update your dependencies
